import rss from '@astrojs/rss';

export async function GET(context) {
  const posts = [
    {
      title: 'Project Glasswing: Securing critical software for the AI era',
      titleZh: 'Project Glasswing: 为 AI 时代保护关键软件',
      pubDate: new Date('2026-04-08'),
      description: 'Anthropic launches initiative to secure the world\'s most critical software and give defenders a durable advantage in the AI-driven cybersecurity era.',
      descriptionZh: 'Anthropic 推出新计划，旨在保护全球最关键软件，为防御者在 AI 驱动的网络安全时代提供持久优势。',
      link: '/blog/project-glasswing-securing-critical-software-for-t',
    },
    {
      title: 'Design UI using AI with Stitch from Google Labs',
      titleZh: 'Google Labs 发布 Stitch：用 AI 设计 UI',
      pubDate: new Date('2026-03-19'),
      description: 'Stitch is evolving into an AI-native platform that allows anyone to create, iterate, and collaborate on high-fidelity UI.',
      descriptionZh: 'Stitch 正在演进为 AI 原生平台，让任何人都能创建、迭代并协作打造高保真 UI。',
      link: '/blog/design-ui-using-ai-with-stitch-from-google-labs',
    },
    {
      title: 'Introducing Forge | Mistral AI',
      titleZh: 'Mistral AI 发布 Forge：企业专有知识驱动的前沿模型系统',
      pubDate: new Date('2026-03-18'),
      description: 'Today, we’re introducing Forge, a system that allows enterprises to build frontier-grade AI models grounded in their proprietary knowledge.',
      descriptionZh: 'Mistral AI 发布 Forge，让企业基于专有知识构建前沿级 AI 模型。',
      link: '/blog/introducing-forge-mistral-ai',
    },
    {
      title: 'Claude Now Creates Interactive Visuals Directly in Chat',
      titleZh: 'Claude 现可直接在对话中生成交互式可视化内容',
      pubDate: new Date('2026-03-18'),
      description: 'Claude now creates interactive charts and diagrams directly in chat. This beta feature lets users explain concepts or analyze data with custom visuals—no coding required. Based on last fall\'s Imagine…',
      descriptionZh: 'Claude 推出对话内嵌可视化功能，可直接生成交互式图表和示意图。该测试版源自去年预览的 Imagine with Claude，用户无需编程即可解释概念或分析数据。',
      link: '/blog/claude-builds-interactive-visuals-right-in-your-co',
    },
    {
      title: 'The 2028 Global Intelligence Crisis: A Bearish Scenario for AI Optimism',
      titleZh: '2028年全球智能危机：AI 乐观主义的熊市情景',
      pubDate: new Date('2026-02-27'),
      description: 'CitriniResearch scenario analysis explores economic risks of rapid AI development: unemployment hits 10.2%, "Ghost GDP", SaaS industry collapse...',
      descriptionZh: 'CitriniResearch 发布情景分析，探讨 AI 快速发展可能带来的经济风险：失业率飙升至 10.2%、"幽灵 GDP"、SaaS 行业崩溃...',
      link: '/blog/2028-global-intelligence-crisis',
    },
    {
      title: 'Jack Dorsey Announces Major Block Layoffs: Reducing from 10,000 to 6,000 Employees',
      titleZh: 'Jack Dorsey 宣布 Block 大规模裁员：从 10,000 人减至 6,000 人',
      pubDate: new Date('2026-02-27'),
      description: 'Block founder Jack Dorsey announces the company will reduce workforce by nearly 50%, from over 10,000 to approximately 6,000 employees. Over 4,000 people will be affected...',
      descriptionZh: 'Block 创始人 Jack Dorsey 宣布公司将裁员近 50%，从超过 10,000 名员工减少至约 6,000 人。超过 4,000 名员工将受到影响...',
      link: '/blog/jack-block-layoffs-2026',
    },
    {
      title: 'Google Releases Nano Banana 2: Next-Gen Image Model Combining Pro Capabilities with Lightning Speed',
      titleZh: 'Google 发布 Nano Banana 2：结合 Pro 能力与闪电速度的新一代图像模型',
      pubDate: new Date('2026-02-27'),
      description: 'Google DeepMind releases Nano Banana 2, combining Pro features with Flash speed. Supports subject consistency, precise text rendering, 4K resolution...',
      descriptionZh: 'Google DeepMind 发布 Nano Banana 2，将 Pro 版本的高级功能与 Flash 的闪电速度相结合。支持主体一致性、精确文本渲染、4K 分辨率...',
      link: '/blog/nano-banana-2-google-image-model',
    },
    {
      title: 'Google Releases Gemini 3.1 Pro: Next-Gen Multimodal Reasoning Model',
      titleZh: 'Google 发布 Gemini 3.1 Pro：新一代多模态推理模型',
      pubDate: new Date('2026-02-20'),
      description: 'Google DeepMind releases Gemini 3.1 Pro, leading on benchmarks including Humanity\'s Last Exam, ARC-AGI-2, and SWE-Bench...',
      descriptionZh: 'Google DeepMind 发布 Gemini 3.1 Pro，在 Humanity\'s Last Exam、ARC-AGI-2、SWE-Bench 等多项基准测试中领先...',
      link: '/blog/gemini-3-1-pro-model-card',
    },
    {
      title: 'Figma: The Future of Design is Code and Canvas',
      titleZh: 'Figma：设计的未来是代码与画布',
      pubDate: new Date('2026-02-18'),
      description: 'Figma introduces Claude Code to Figma, allowing developers to convert code directly into editable designs...',
      descriptionZh: 'Figma 推出 Claude Code to Figma 功能，让开发者可以直接将代码转换为可编辑的设计稿...',
      link: '/blog/figma-future-of-design-code-canvas',
    },
    {
      title: 'RynnBrain: Alibaba\'s Open Embodied Foundation Model',
      titleZh: 'RynnBrain：阿里巴巴开源具身智能基础模型',
      pubDate: new Date('2026-02-15'),
      description: 'Alibaba DAMO Academy releases RynnBrain, an embodied foundation model grounded in physical reality...',
      descriptionZh: '阿里巴巴达摩院发布 RynnBrain，一个基于物理现实的具身基础模型...',
      link: '/blog/rynnbrain-alibaba-embodied-model',
    },
    {
      title: 'Entire: A Collaboration Platform for Agents and Humans',
      titleZh: 'Entire：智能体与人类的协作平台',
      pubDate: new Date('2026-02-11'),
      description: 'Entire is going beyond repositories, building a developer platform where agents and humans can collaborate, interact, and grow.',
      descriptionZh: 'Entire 正在超越代码仓库，构建一个开发者平台，让智能体和人类能够协作、互动和成长。',
      link: '/blog/entire',
    },
    {
      title: 'AI Hires Humans: A New Paradigm in the Agent Economy',
      titleZh: 'AI 雇佣人类：智能体经济的新范式',
      pubDate: new Date('2026-02-09'),
      description: 'Rent a Human introduces a disruptive concept where AI agents hire humans for physical tasks...',
      descriptionZh: 'Rent a Human 提出颠覆性概念：AI 智能体雇佣人类完成物理任务...',
      link: '/blog/ai-hires-humans',
    },
    {
      title: 'Google Announced Agent Payments Protocol (AP2)',
      titleZh: 'Google 发布 Agent Payments Protocol (AP2)',
      pubDate: new Date('2025-09-16'),
      description: 'Google announced AP2, an open protocol built on A2A that enables secure payment transactions between AI agents...',
      descriptionZh: 'Google 发布 AP2 协议，一个建立在 A2A 之上的开放标准，支持 AI 智能体之间的安全支付交易...',
      link: '/blog/google-announced-agent-payments-protocol-ap2',
    },
    {
      title: 'Google Introduces A2A Protocol: A New Era of Agent Interoperability',
      titleZh: 'Google 推出 A2A 协议：智能体互操作的新时代',
      pubDate: new Date('2025-04-09'),
      description: 'Google announces A2A open protocol enabling agents from different frameworks and vendors to collaborate...',
      descriptionZh: 'Google 宣布 A2A 开放协议，让不同框架和供应商的智能体能够协作...',
      link: '/blog/google-a2a-protocol',
    },
    {
      title: 'Anthropic Introduces Model Context Protocol (MCP)',
      titleZh: 'Anthropic 发布 Model Context Protocol (MCP)',
      pubDate: new Date('2024-11-25'),
      description: 'Anthropic open-sources MCP, an open standard connecting AI assistants to data systems...',
      descriptionZh: 'Anthropic 开源 MCP，一个连接 AI 助手与数据系统的开放标准...',
      link: '/blog/anthropic-model-context-protocol',
    },
  ];

  return rss({
    title: 'Agent Economy',
    description: 'Curated news and insights about AI agents and the autonomous economy | 关于 AI 智能体经济的精选洞察',
    site: context.site,
    items: posts.map((post) => ({
      title: `${post.title} | ${post.titleZh}`,
      description: `${post.description} / ${post.descriptionZh}`,
      pubDate: post.pubDate,
      link: `${context.site}${post.link}`,
    })),
    customData: `<language>en-us</language>`,
  });
}
